config/routes.rb
Rails.application.routes.draw do
  
  resources :tickets
  get '/dashboard', to: 'page#dashboard'
  get '/settings', to: 'page#settings'
  get '/tracking', to: 'page#tracking', as: :tracking
  
  resources :events
  resources :devices

  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  authenticated :user do
    root to: redirect('/tracking')
  end
  
  unauthenticated :user do
    devise_scope :user do
      root to: "users/sessions#new", as: "unauthenticated"
    end
  end

  

end

app/models/device.rb
class Device < ActiveRecord::Base
    has_many :device_histories
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:barcode, :serial, :service_tag, :type, :make, :model)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :barcode %><br>
    <%= f.text_field :barcode %>
  </div>
  <div class="field">
    <%= f.label :serial %><br>
    <%= f.text_field :serial %>
  </div>
  <div class="field">
    <%= f.label :service_tag %><br>
    <%= f.text_field :service_tag %>
  </div>
  <div class="field">
    <%= f.label 'Device Model' %> <i class='glyphicon glyphicon-plus-sign'></i><br>
    <%= f.collection_select :device_model_id, DeviceModel.order(:name), :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-lg-12'>
    
      <h1>Devices</h1>
      
      <table>
        <thead>
          <tr>
            <th>Barcode</th>
            <th>Serial</th>
            <th>Service tag</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @devices.each do |device| %>
            <tr>
              <td><%= device.barcode %></td>
              <td><%= device.serial %></td>
              <td><%= device.service_tag %></td>

              <td><%= link_to 'Show', device %></td>
              <td><%= link_to 'Edit', edit_device_path(device) %></td>
              <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
      <%= link_to 'New Device', new_device_path %>
      
    </div>
  </div>
</div>

app/views/devices/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-lg-12'>

    <h1>New Device</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Back', devices_path %>
    
    </div>
  </div>
</div>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Barcode:</strong>
  <%= @device.barcode %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @device.serial %>
</p>

<p>
  <strong>Service tag:</strong>
  <%= @device.service_tag %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>